# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Helper\ApiHelper:
        arguments:
            $baseApiUrl: '%env(TILE_EXPERT_BASE_URL)%'

    App\Repository\:
        resource: '../src/Repository/'
        tags: [ 'doctrine.repository_service' ]

    App\Service\PriceParse\PriceParserService:
        arguments:
            $apiHelper: '@App\Helper\ApiHelper'

    App\Service\Order\OrderService:
        arguments:
            $orderRepository: '@App\Repository\OrderRepository'
            $deliveryRepository: '@App\Repository\OrderDeliveryRepository'
            $articlesRepository: '@App\Repository\OrderArticlesRepository'
            $serializer: '@serializer'
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\Manticore\ManticoreSearchService:
        arguments:
            $httpClient: '@http_client'
            $baseManticoreUrl: '%env(MANTICORE_URL)%'
#            $manticoreHost: '%env(MANTICORE_HOST)%'
#            $manticorePort: '%env(MANTICORE_HTTP_PORT)%'

    App\Controller\PriceController:
        arguments:
            $priceParser: '@App\Service\PriceParse\PriceParserService'

    App\Controller\OrderController:
        arguments:
            $orderService: '@App\Service\Order\OrderService'

    App\Controller\SoapOrderController:
        arguments:
            $orderService: '@App\Service\Order\OrderService'
            $parameterBag: '@parameter_bag'

    App\Controller\SearchController:
        arguments:
            $searchService: '@App\Service\Manticore\ManticoreSearchService'

    App\DataFixtures\:
        resource: '../src/DataFixtures/*'
        tags: [ 'doctrine.fixture.orm' ]

    App\Command\IndexArticlesCommand:
        tags: [ 'console.command' ]
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $searchService: '@App\Service\Manticore\ManticoreSearchService'
